let shopItemsData = [
  {
    id: "kdafnidas",
    imageSrc: "/assets/dessert-img.webp",
    alt: "Desert od šljive",
    detailTitle: "Desert od šljive 90 grama, izvor biotina i vlakana",
    price: 139.0,
    formSubmitetDetail: "Desert od šljive",
    linkTo: "/pojedinačni-proizvod/desert-od-šljive.html",
  },
  {
    id: "tdgfnidas",
    imageSrc: "/assets/orasnice.webp",
    alt: "Orasnica",
    detailTitle: "Orasnica 50 grama, izvor vitamina i minerala",
    price: 89.0,
    formSubmitetDetail: "Orasnica",
    linkTo: "/pojedinačni-proizvod/orasnica.html",
  },
  {
    id: "gdafsidas",
    imageSrc: "/assets/med_i_suncokret.webp",
    alt: "Pločica od semenki suncokreta i livadskog meda",
    detailTitle:
      "Pločica od semenki suncokreta i livadskog meda 50 grama, proizvod sa 10 benefita",
    price: 89.0,
    formSubmitetDetail: "Pločica",
    linkTo:
      "/pojedinačni-proizvod/pločica-od-semenki-suncokreta-i-livadskog-meda.html",
  },
  {
    id: "jdaffidas",
    imageSrc: "/assets/desert_od_sljive_i_oraha.webp",
    alt: "Desert od šljive i oraha",
    detailTitle: "Desert od šljive i oraha 50 grama",
    price: 89.0,
    formSubmitetDetail: "Desert od šljive i oraha",
    linkTo: "/pojedinačni-proizvod/desert-od-šljive-i-oraha.html",
  },
  {
    id: "ddafnid00",
    imageSrc: "/assets/ulje_od_kostica_sljive.webp",
    alt: "Ulje od koštica šljive 250 ml",
    detailTitle: "Ulje od koštica šljive 250 ml, izvor vitamina E",
    price: 2000.0,
    formSubmitetDetail: "Ulje od koš. šlj. 250ml",
    linkTo: "/pojedinačni-proizvod/ulje-od-koštica-šljive-250ml.html",
  },
  {
    id: "qddf4idas",
    imageSrc: "/assets/ulje_od_kostica_sljive.webp",
    alt: "Ulje od koštica šljive 100 ml",
    detailTitle: "Ulje od koštica šljive 100 ml, izvor vitamina E",
    price: 800.0,
    formSubmitetDetail: "Ulje od koš. šlj. 100ml",
    linkTo: "/pojedinačni-proizvod/ulje-od-koštica-šljive-100ml.html",
  },
  {
    id: "caafgidas",
    imageSrc: "/assets/orahovo_ulje.webp",
    alt: "Ulje od oraha 250 ml",
    detailTitle:
      "Ulje od oraha 250 ml, izvor vitamina i omega 3 masnih kiselina",
    price: 2000.0,
    formSubmitetDetail: "Ulje od oraha 250ml",
    linkTo: "/pojedinačni-proizvod/ulje-od-oraha-250ml.html",
  },
  {
    id: "fdaf6icas",
    imageSrc: "/assets/orahovo_ulje.webp",
    alt: "Ulje od oraha 100 ml",
    detailTitle:
      "Ulje od oraha 100 ml, izvor vitamina i omega 3 masnih kiselina",
    price: 800.0,
    formSubmitetDetail: "Ulje od oraha 100ml",
    linkTo: "/pojedinačni-proizvod/ulje-od-oraha-100ml.html",
  },
];
